[[PhotoCollage]]
== Photo Collage

[[Description]]
[.lead]
Photo collage is a graphical tool/application used to gather a user's image gallery data and make collage posters according to the user's design or the results of the inbuilt algorithm.

== Benefits
There are many difficulties in creating poster designs, collage layouts, and managing proportions in imagery such that users are attracted to your works from clever use of color palettes, sizing, and layouts. PhotoCollage's algorithms solve these problems for the user, streamlining the process, allowing for easy use of the application yet still providing results for the commercial market.

[[HowToUse]]
=== How to use

[start=1]
. Download the installation files from 

= Installation

:hide-uri-scheme:

https://github.com/adrienverge/PhotoCollage[PhotoCollage Repository] 

[%hardbreaks]
2.1. On Fedora run *_sudo dnf install PhotoCollage_* in the terminal 
[%hardbreaks]
2.2. On Debian 9+ run *_sudo apt-get install photocollage_* 
[%hardbreaks]
2.3. On pip Python manager run *_sudo pip3 install photocollage_*
[%hardbreaks]

. Run installation wizard.
. After installation, a launcher for PhotoCollage will appear in your desktop menu.
. Run the command 'PhotoCollage' in the terminal.

== UserFeedback
With 352 stars on Github, PhotoCollage has a following of users that are satisfied with its performance and features. More updates are being released for the product, having its documentation translated into Ukrainian and Brazilian Portuguese language in recent patches. Thus reaching more users in the market.
